name: ardupilot_gazebo_ros2
services:
  ros2:
    image: osrf/ros:humble-desktop-full
    container_name: ros2-humble
    environment:
        DISPLAY: host.docker.internal:0.0
    ports:
        - "10000:10000"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash